### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by open-git** [j178/tiktoken-go#1]
/usr/local/opt/go/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
clang: error: no such file or directory: '/xxx/gopath/pkg/mod/github.com/j178/tiktoken-go@v0.2.1/tiktoken-cffi/target/release/libtiktoken.a'

**Comment by j178** [comment]
This project can not be used as a module, you should clone it and put it inside your project, and build the cffi library yourself.

Anyway, this project is just a experiment and not recommended. Here are some pure Go implementations you might consider using instead of this one:

- https://github.com/pkoukk/tiktoken-go
- https://github.com/tiktoken-go/tokenizer
